update docs link on readme
iak-id/iak-api-php pull request #8
Opened 2021-06-10 09:59 UTC by alvinvaja

2021-06-10 15:19 UTC, echr requested changes

2021-06-10 15:19 UTC, echr commented on README.md
> +You can find the documentation of this package at [API SDK docs](https://api.iak.id/docs/sdk/docs/introduction.md)
Pakai link ini aja kali..

https://api.iak.id/docs/sdk/docs/php/introduction.md

2021-06-10 15:24 UTC, alvinvaja commented on README.md
> +You can find the documentation of this package at [API SDK docs](https://api.iak.id/docs/sdk/docs/introduction.md)
Baik kak

2021-06-14 05:51 UTC, echr approved these changes

2021-06-14 07:35 UTC, merged